test:
  msg: hello world
server:
  port: 8887

spring:
  application:
    name: service-consumer

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka/

feign:
  hystrix:
    enabled: true
